### ISSUE TITLE
Add the option to change the address and port the http server is listening on based on the cmd arguments.

### ISSUE THREAD

**Issue by Samurahh** [Samurahh/go-short#2]
At the moment, there is no way to change the address and port the http server is listening on other than the one hard-coded.

This feature, should allow the following usage:

go-short [options]

Options:
-p, --port {integer} // -p 8080, --port 8080
--address {string} // --address 10.11.12.13

**Comment by kevinanielsen** [comment]
I'd like to take a go at this - Could I be assigned?

**Comment by Samurahh** [comment]
By default, the http server should listen to all interfaces on port 8080

**Comment by kevinanielsen** [comment]
Okay, I'll take a crack at it!

**Comment by Samurahh** [comment]
I have updated the description of this issue to make it more clear. I did not expect to assign those to anyone else than myself.
